APPLICATION_NAME = Updater
APP_ID = me.devbug.backgrounderxforios5

Updater_BUNDLE_NAME = TrueMultitasking
Updater_OBJC_FILES = main.m
Updater_CFLAGS = -std=gnu99 -DAPP_ID=\"$(APP_ID)\" -DCURRENT_VERSION=$(CURRENT_VERSION)
Updater_PRIVATE_FRAMEWORKS = SpringBoardServices

include ../theos/makefiles/common.mk
include ../theos/makefiles/application.mk
